build:
  nodes:
    analysis:
      tests:
        override:
        - php-scrutinizer-run
    tests:
      override:
        -
          command: "vendor/bin/phpunit"
          coverage:
            file: build/clover.xml
            format: clover
filter: 
  excluded_paths: 
    - tests/*
