language: php

php:
  - 7.1
  - 7.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - COMPOSER_DISCARD_CHANGES=1 composer update --prefer-dist --no-interaction --no-suggest
script:
  - composer test
